### ISSUE TITLE
Support bar charts

### ISSUE THREAD

**Issue by smanousopoulos** [DAIAD/react-echarts#5]
Ideally also add support for: 
- color palette in the same series (as in https://ecomfe.github.io/echarts/doc/example/bar14.html#-en) 
- horizontal bar charts
- option to display value ontop of each bar (as in https://ecomfe.github.io/echarts/doc/example/bar10.html#-en)

**Comment by drmalex07** [comment]
Moved horizontal view as a separate issue #8 (as it is not bound only to bar charts)
