### ISSUE TITLE
Allow changing axes text style 

### ISSUE THREAD

**Issue by smanousopoulos** [DAIAD/react-echarts#6]
Permit passing extra props to change font size and styling for x, y axes (https://ecomfe.github.io/echarts/doc/doc-en.html#TextStyle)

**Comment by drmalex07** [comment]
This can be addressed by simply providing a theme variation. We'd rather not clutter the props interface with numerous theme-only options.

A working example can be found at 870f62218557306cd7f08d3e8c40b606b930a416 (a derived theme is created as https://github.com/DAIAD/react-echarts/blob/870f62218557306cd7f08d3e8c40b606b930a416/example/src/js/theme/whiteboard-1.js)
